_wandb:
    value:
        cli_version: 0.26.1
        e:
            43cwx6i0pvjdzikaobsaqgf1c88kjy2e:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "259368415232"
                        used: "231662387200"
                email: dionatanschmidt@unipampa.edu.br
                executable: C:\dev\tune3\.venv\Scripts\python.exe
                host: Schmidt
                memory:
                    total: "16849293312"
                os: Windows-11-10.0.26200-SP0
                program: C:\dev\tune3\main.py
                python: CPython 3.12.2
                root: C:\dev\tune3
                startedAt: "2026-05-29T19:24:02.974597Z"
                writerId: 43cwx6i0pvjdzikaobsaqgf1c88kjy2e
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 50
                - 53
            "2":
                - 1
                - 5
                - 35
                - 41
                - 50
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.2
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
